version: "3.8"

services:
  app:
    build: ./app
    container_name: claims-app
    ports:
      - "3000:3000"
    mem_limit: 256m
    restart: always
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro   # Gives container access to host filesystem (read-only)
      - /var/run:/var/run:ro # Access to Docker runtime socket
      - /sys:/sys:ro  # Access to system metrics like CPU, memory, etc.
      - /var/lib/docker/:/var/lib/docker:ro  # Access to Docker container data
    restart: unless-stopped
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # Mounts Prometheus configuration file
      - ./prometheus/slo_rules.yml:/etc/prometheus/slo_rules.yml   # Mounts SLO alert rules
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor
    restart : unless-stopped 
  
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
          - ./grafana/provisioning:/etc/grafana/provisioning # Automatically  loads data sources and dashboards from the provisioning directory
          - ./grafana/dashboards:/var/lib/grafana/dashboards # Mounts custom dashboards like(heap memory,restart count,latency, error rates, etc.)
    depends_on:
      - prometheus
    restart : unless-stopped
  
  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml # Mounts Loki configuration file
      - ./loki-data:/loki # Persistent storage for Loki logs
    command: -config.file=/etc/loki/loki-config.yaml # Specifies the path to the Loki configuration file to use when the container starts
    restart: unless-stopped
  

  promtail:
   image: grafana/promtail:latest
   container_name: promtail
   user: root # Runs as root so it can access Docker logs 
   environment:
     - DOCKER_API_VERSION=1.44
   volumes:
    - /var/run/docker.sock:/var/run/docker.sock # allows promtail to read Docker container logs 
    - /var/lib/docker/containers:/var/lib/docker/containers:ro # Access to Docker container logs (read-only)
    - ./promtail-config.yaml:/etc/promtail/promtail.yaml # Mounts Promtail configuration file
   command: -config.file=/etc/promtail/promtail.yaml # Starts promtail using that configuration file
   depends_on:
    - loki
   restart: unless-stopped
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
    - "16686:16686"
    - "14268:14268"
    restart: unless-stopped
  
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,iam,kafka
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"