global:
  scrape_interval: 5s

rule_files:
  - slo_rules.yml

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "claims-app"
    static_configs:
      - targets: ["app:3000"]