apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: claims-processor-policy
spec:
  podSelector:
    matchLabels:
      app: claims-processor
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: ingress-nginx
      ports:
        - protocol: TCP
          port: 3000