apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: claims-chaos-cpu-stress
  namespace: default
spec:
  appinfo:
    appns: default
    applabel: 'app=claims-processor'
    appkind: deployment
  engineState: active
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-cpu-hog
      spec:
        components:
          env:
            - name: CPU_CORES
              value: '2'
            - name: TOTAL_CHAOS_DURATION
              value: '120'