apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: claims-chaos-pod-delete
  namespace: default
spec:
  appinfo:
    appns: default
    applabel: 'app=claims-processor'
    appkind: deployment
  engineState: active
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '60'
            - name: CHAOS_INTERVAL
              value: '10'
            - name: FORCE
              value: 'false'